// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCiygsB217lgcGB2VkDEW4UHtVz7w3Wn50',
    appId: '1:856414201471:web:762423180b6dbead06c14a',
    messagingSenderId: '856414201471',
    projectId: 'eduapp-46567',
    authDomain: 'eduapp-46567.firebaseapp.com',
    storageBucket: 'eduapp-46567.firebasestorage.app',
    measurementId: 'G-56F1SRG857',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAELvONANjrl6gOMF7Uf8Pddo3koJd0PlI',
    appId: '1:856414201471:android:117e6c95c64217c606c14a',
    messagingSenderId: '856414201471',
    projectId: 'eduapp-46567',
    storageBucket: 'eduapp-46567.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBtXf7AeiY0BK2mDk3grFFGEA_DMtBIXaQ',
    appId: '1:856414201471:ios:98b2e9a34cbb222206c14a',
    messagingSenderId: '856414201471',
    projectId: 'eduapp-46567',
    storageBucket: 'eduapp-46567.firebasestorage.app',
    iosBundleId: 'com.example.eduApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBtXf7AeiY0BK2mDk3grFFGEA_DMtBIXaQ',
    appId: '1:856414201471:ios:98b2e9a34cbb222206c14a',
    messagingSenderId: '856414201471',
    projectId: 'eduapp-46567',
    storageBucket: 'eduapp-46567.firebasestorage.app',
    iosBundleId: 'com.example.eduApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCiygsB217lgcGB2VkDEW4UHtVz7w3Wn50',
    appId: '1:856414201471:web:655bc6f506d97a4a06c14a',
    messagingSenderId: '856414201471',
    projectId: 'eduapp-46567',
    authDomain: 'eduapp-46567.firebaseapp.com',
    storageBucket: 'eduapp-46567.firebasestorage.app',
    measurementId: 'G-R1RJ7FKTV8',
  );
}
